# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: Azure Pipelines

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'sirconnnection'
    KeyVaultName: 'kaikonkey'
    SecretsFilter: 'pcadmin'
    RunAsPreJob: false
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'sirconnnection'
    subscriptionId: '7218e9da-1d29-4917-b2eb-e2c7e5a75de7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'devpiperm'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    overrideParameters: '-adminPassword $(Pcadmin)'
    deploymentMode: 'Incremental'
    deploymentName: 'TemplateDeploy'